spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dumbo.db.elephantsql.com/nqtejdhb?sslmode=require
    username: nqtejdhb
    password: DNCCHOYjLslmgANbC8okLeN0LiXcA_Ur
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
      generate-ddl: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
